//! Generate the reference pages, so that nobody maintains them by hand.
//!
//! A reference page is a list of things the code already knows: the flags the
//! binary prints, the routes the router registers, the keys the config parser
//! reads. Written by hand, every one of them is a promise that decays the first
//! time someone adds a route and does not think of the docs. Nobody notices,
//! because a docs page cannot fail a test.
//!
//! So the code is the source and these pages are the output:
//!
//! ```text
//! docs/reference/cli.md    <- `mira --help`, verbatim, from the built binary
//! docs/reference/http.md   <- `.route(...)` calls + the handler's doc comment
//! docs/config.md           <- the `KNOWN` key list + `Config`'s field docs,
//!                             injected between markers so the prose survives
//! ```
//!
//! `make reference` writes them; `make reference-check` writes them and then
//! `git diff --exit-code`s, which is what CI runs. That is the same shape as the
//! committed UI bundle and the generated chart README: the artefact is in git so
//! a reader gets it without a build, and a pull request that changes the code
//! without regenerating goes red.
//!
//! Descriptions come from doc comments, which is the second half of the point:
//! rustdoc publishes the *whole* comment at miradb.dev/api/, this takes the
//! first paragraph of the same comment for the summary table, and there is one
//! text to keep true rather than two.

use std::collections::BTreeMap;
use std::process::Command;

use regex::Regex;

use crate::util::{Failures, glob, re, read_or_exit, root};

const SRC: &str = "crates/mira/src";

/// Where the rustdoc for a symbol lives once `make site` has published it. The
/// summary tables link into it, so "the rest of the comment" is one click from
/// every row rather than a file path a reader has to go and clone.
const RUSTDOC: &str = "https://miradb.dev/api";

const STAMP: &str = "<!-- Generated by `cargo run -p xtask -- reference` from the code it documents.\n     Do not edit: run `make reference`. -->";

pub fn run() -> bool {
    let mut f = Failures::default();
    let mut changed = false;
    changed |= write("docs/reference/cli.md", &cli_page(&mut f));
    changed |= write("docs/reference/http.md", &http_page(&mut f));
    changed |= inject("docs/config.md", "keys", &config_table(&mut f), &mut f);
    changed |= inject(
        "docs/config.md",
        "count",
        &known_keys(&mut f).to_string(),
        &mut f,
    );
    check_rustdoc_links(&mut f);

    if !f.report("reference check(s) failed") {
        return false;
    }
    println!(
        "{}",
        if changed {
            "reference regenerated."
        } else {
            "reference up to date."
        }
    );
    true
}

// ---------------------------------------------------------------------------
// Reading Rust
// ---------------------------------------------------------------------------

/// A doc comment is the run of `///` lines immediately above an item. Rust has
/// no other place to put one, so this is the whole grammar.
fn doc_line() -> Regex {
    re(r"^\s*///(.*)$")
}

/// The `///` block ending at line `i - 1`, outermost line first.
fn doc_above(lines: &[&str], i: usize) -> Vec<String> {
    let pat = doc_line();
    let mut out = Vec::new();
    for line in lines[..i].iter().rev() {
        let Some(m) = pat.captures(line) else {
            // `#[attr]` sits between the doc comment and the item it documents.
            if line.trim_start().starts_with("#[") {
                continue;
            }
            break;
        };
        out.push(m[1].trim().to_string());
    }
    out.reverse();
    out
}

/// The summary sentence: everything up to the first blank line, joined.
///
/// `[`Config::wal`]` is a rustdoc intra-doc link, and Markdown reads it as a
/// reference-style link to a definition that does not exist on the page. The
/// brackets come off; the code span stays. A `](` after it means the author
/// wrote a real link, which is left alone — hence the check on what follows
/// rather than a negative lookahead, which this regex engine does not have and
/// does not need.
fn first_paragraph(doc: &[String]) -> String {
    let joined = doc
        .iter()
        .take_while(|l| !l.is_empty())
        .cloned()
        .collect::<Vec<_>>()
        .join(" ");
    let joined = joined.trim();
    let pat = re(r"\[(`[^`]+`)\]");
    let mut out = String::with_capacity(joined.len());
    let mut last = 0;
    for m in pat.captures_iter(joined) {
        let whole = m.get(0).expect("group 0");
        if joined[whole.end()..].starts_with('(') {
            continue;
        }
        out.push_str(&joined[last..whole.start()]);
        out.push_str(&m[1]);
        last = whole.end();
    }
    out.push_str(&joined[last..]);
    out
}

/// The `//` block ending at line `i - 1`, for the routes a macro builds.
///
/// A macro expansion is not an item, so it cannot carry a doc comment and
/// rustdoc will never see it. The three OTLP export routes are the whole of that
/// case; an ordinary comment above the `.route(` line is where their description
/// lives, and the generator says so out loud rather than silently emitting a
/// blank cell.
fn comment_above(lines: &[&str], i: usize) -> String {
    let mut out: Vec<&str> = Vec::new();
    for line in lines[..i].iter().rev() {
        let t = line.trim_start();
        if !t.starts_with("//") || t.starts_with("///") {
            break;
        }
        out.push(t[2..].trim());
    }
    out.reverse();
    out.join(" ").trim().to_string()
}

/// Every free function in a file, name -> body text.
///
/// A body ends at the first line that is a bare `}`, which is true of every
/// function in this tree because rustfmt puts it there.
fn functions(text: &str) -> BTreeMap<String, String> {
    let lines: Vec<&str> = text.split('\n').collect();
    let mut out = BTreeMap::new();
    for m in fn_decl().captures_iter(text) {
        let i = line_index(text, m.get(0).expect("group 0").start());
        let mut j = i + 1;
        while j < lines.len() && lines[j] != "}" {
            j += 1;
        }
        out.insert(m[1].to_string(), lines[i..j].join("\n"));
    }
    out
}

fn fn_decl() -> Regex {
    re(r"(?m)^(?:pub(?:\([a-z:]+\))? )?(?:async )?fn ([a-z_][a-z0-9_]*)")
}

/// The 0-indexed line containing byte offset `at`.
fn line_index(text: &str, at: usize) -> usize {
    text[..at].matches('\n').count()
}

// ---------------------------------------------------------------------------
// The HTTP surface
// ---------------------------------------------------------------------------

fn route_call() -> Regex {
    re("\\.route\\(\\s*\n?\\s*\"([^\"]+)\"\\s*,\\s*([^\n]*)")
}

fn handler() -> Regex {
    re(r"(?:axum::routing::)?(get|post)\(\s*([A-Za-z_][A-Za-z0-9_]*)")
}

/// What each status the handlers emit means to a caller.
///
/// Keyed on the Rust constant, so a new one added to a handler lands here as a
/// failure rather than as a table that quietly stops being the whole list. The
/// order is the order the table prints in.
const STATUS: [(&str, &str, &str); 9] = [
    ("OK", "200", "The answer, as the envelope below."),
    (
        "BAD_REQUEST",
        "400",
        "The document did not parse, named a key no endpoint accepts, or gave a \
         value out of range. The body is `{\"error\": \"...\"}` — JSON, like the \
         success, so a caller has one thing to parse.",
    ),
    (
        "INTERNAL_SERVER_ERROR",
        "500",
        "The read failed or its thread panicked. The body is the error text.",
    ),
    (
        "PAYLOAD_TOO_LARGE",
        "413",
        "The export was larger than `ingest.max_request_bytes`.",
    ),
    (
        "SERVICE_UNAVAILABLE",
        "503",
        "The signal's queue is full and the export was shed. Retry it: this is \
         backpressure, not a failure, and `ingest.queue` is how much of it an \
         operator buys away.",
    ),
    (
        "UNSUPPORTED_MEDIA_TYPE",
        "415",
        "The export was not protobuf.",
    ),
    (
        "ACCEPTED",
        "202",
        "An OTLP export was queued, or an MCP notification was taken. Accepted \
         means durable when `ingest.wal` is on and queued when it is off.",
    ),
    (
        "NOT_MODIFIED",
        "304",
        "A UI asset the caller already has. The bundle is built into the binary, \
         so its ETag is its content hash.",
    ),
    ("NOT_FOUND", "404", "No such UI asset."),
];

/// An Arrow type as "what may I compare this against".
///
/// Anything not here is a column no term can usefully match, and is left out of
/// the table rather than listed with a type a caller cannot write in KYAML.
const COMPARABLE: [(&str, &str); 12] = [
    ("DataType::Utf8", "string"),
    ("dict_u16_utf8", "string"),
    ("DataType::Int32", "number"),
    ("DataType::Int64", "number"),
    ("DataType::UInt8", "number"),
    ("DataType::UInt16", "number"),
    ("DataType::UInt32", "number"),
    ("DataType::UInt64", "number"),
    ("DataType::Float64", "number"),
    ("DataType::Boolean", "boolean"),
    ("ts", "nanoseconds"),
    ("DataType::FixedSizeBinary", "hex string"),
];

/// Which root schema each `signal` value queries. `Signal::parse` maps the name
/// and `search_open` reads the root batch, so these two are the whole of what a
/// `field` term can name.
const SIGNAL_SCHEMA: [(&str, &str); 2] = [("logs", "LOGS"), ("traces", "SPANS")];

/// `e2e.rs` is the in-process end-to-end suite, not a surface. The statuses in
/// it are the ones it asserts on, and listing them here would document the
/// tests.
const NOT_A_SURFACE: [&str; 1] = ["e2e.rs"];

/// Routes are grouped the way a reader meets them, not the way the files happen
/// to sort. The port is part of the answer: everything below is on `listen.http`
/// except the gRPC service, which is not a route at all.
const GROUPS: [(&str, &[&str]); 5] = [
    ("Ingest", &["/v1/logs", "/v1/traces", "/v1/metrics"]),
    (
        "Query",
        &[
            "/api/v1/query",
            "/api/v1/metrics/query",
            "/api/v1/metrics/names",
            "/api/v1/correlate",
            "/api/v1/map",
            "/api/v1/entities",
        ],
    ),
    ("Agents", &["/mcp"]),
    (
        "Operate",
        &["/health", "/readyz", "/api/v1/stats", "/api/v1/alerts"],
    ),
    ("Web UI", &["/", "/{file}"]),
];

/// Every registered route: path -> (method, module, summary).
fn routes(f: &mut Failures) -> BTreeMap<String, (String, String, String)> {
    let mut found = BTreeMap::new();
    for path in glob(&format!("{SRC}/*.rs")) {
        let name = path.rsplit('/').next().unwrap_or(&path).to_string();
        let stem = name.trim_end_matches(".rs").to_string();
        let text = read_or_exit(&path);
        let lines: Vec<&str> = text.split('\n').collect();

        for m in route_call().captures_iter(&text) {
            let route = m[1].to_string();
            let rest = &m[2];
            let i = line_index(&text, m.get(0).expect("group 0").start());
            let (method, summary) = if let Some(h) = handler().captures(rest) {
                let fname = &h[2];
                // The handler's own doc comment, wherever it is in this file.
                let decl = re(&format!(r"(?m)^(?:async )?fn {}\b", regex::escape(fname)));
                let summary = decl
                    .find(&text)
                    .map(|m| first_paragraph(&doc_above(&lines, line_index(&text, m.start()))))
                    .unwrap_or_default();
                if summary.is_empty() {
                    f.fail(format!(
                        "{name}: handler `{fname}` for {route} has no doc comment. The \
                         reference table takes its first paragraph, and a route nobody \
                         can describe in one sentence is a route nobody should be \
                         shipping."
                    ));
                }
                (h[1].to_uppercase(), summary)
            } else {
                let Some(mac) = re(r"([a-z_]+)!\(").captures(rest) else {
                    f.fail(format!(
                        "{name}: cannot read the handler of {route}: {rest:?}"
                    ));
                    continue;
                };
                // `macro_rules! signal { ... => { post( ... ) } }`: the method is
                // the first routing constructor in the macro body.
                let body = text
                    .rsplit_once(&format!("macro_rules! {}", &mac[1]))
                    .map_or_else(|| text.clone(), |(_, tail)| tail.to_string());
                let method = re(r"\b(get|post)\(")
                    .captures(&body)
                    .map_or_else(|| "?".to_string(), |m| m[1].to_uppercase());
                let summary = comment_above(&lines, i);
                if summary.is_empty() {
                    f.fail(format!(
                        "{name}: {route} is built by a macro, so it has no doc comment. \
                         Put a `//` comment on the line above the `.route(` call; that \
                         is where this table reads it."
                    ));
                }
                (method, summary)
            };
            found.insert(route, (method, stem.clone(), summary));
        }
    }
    found
}

/// The closed key set a handler's parser enforces, found transitively.
///
/// A handler calls `parse_search`, which calls `search_doc`, which is where the
/// `known(...)` is. Following the calls is what makes this survive someone
/// moving the check one function further down. The walk order comes back too: it
/// is also where the example belongs, and guessing the parser's name from the
/// handler's only works until one of them is renamed.
fn accepted_keys(fns: &BTreeMap<String, String>, entry: &str) -> (Vec<String>, Vec<String>) {
    let known_call = re(r"(?s)known\(\s*(?:&?doc|y)\s*,\s*&\[([^\]]*)\]");
    let calls = re(r"\b([a-z_][a-z0-9_]*)\s*\(");
    let quoted = re(r#""([^"]+)""#);

    let mut seen: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    let mut order = Vec::new();
    let mut queue = std::collections::VecDeque::from([entry.to_string()]);
    while let Some(fname) = queue.pop_front() {
        let Some(body) = fns.get(&fname) else {
            continue;
        };
        if !seen.insert(fname.clone()) {
            continue;
        }
        order.push(fname);
        if let Some(m) = known_call.captures(body) {
            let keys = quoted
                .captures_iter(&m[1])
                .map(|k| k[1].to_string())
                .collect();
            return (keys, order);
        }
        queue.extend(calls.captures_iter(body).map(|m| m[1].to_string()));
    }
    (Vec::new(), order)
}

/// The ```` ```yaml ```` block from the first of `names` whose doc comment has
/// one.
///
/// Read off the raw lines rather than through [`doc_above`], which strips each
/// one: the indentation inside a fenced block is the example, and a request body
/// flattened to column zero is one a reader has to re-format before it reads as
/// the nested document it is.
fn example(lines: &[&str], text: &str, names: &[String]) -> Vec<String> {
    let pat = doc_line();
    for name in names {
        let decl = re(&format!(
            r"(?m)^(?:pub(?:\([a-z:]+\))? )?(?:async )?fn {}\b",
            regex::escape(name)
        ));
        let Some(at) = decl.find(text) else { continue };
        let mut out: Vec<String> = Vec::new();
        for line in lines[..line_index(text, at.start())].iter().rev() {
            let Some(m) = pat.captures(line) else { break };
            out.push(m[1].strip_prefix(' ').unwrap_or(&m[1]).to_string());
        }
        out.reverse();
        if let Some(i) = out.iter().position(|l| l == "```yaml") {
            let end = out[i + 1..]
                .iter()
                .position(|l| l == "```")
                .map_or(out.len(), |j| i + 1 + j + 1);
            return out[i..end].to_vec();
        }
    }
    Vec::new()
}

/// `3_600_000_000_000` as the duration an operator would write.
fn nanos(literal: &str) -> String {
    let n = literal.replace('_', "").parse::<u64>().unwrap_or_default() / 1_000_000_000;
    for (unit, size) in [("d", 86400), ("h", 3600), ("m", 60)] {
        if n % size == 0 {
            return format!("{}{unit}", n / size);
        }
    }
    format!("{n}s")
}

/// Everything about a query endpoint that is not its path.
struct Detail {
    keys: Vec<String>,
    example: Vec<String>,
    field: String,
    /// Three endpoints answer "right now" to an empty body, and that is the
    /// shortest useful request against a fresh node.
    optional: bool,
}

/// Everything the "Request bodies" half of the page is made of.
struct Bodies {
    detail: BTreeMap<String, Detail>,
    /// The fields of the response `stats` object.
    stats: Vec<String>,
    /// The statuses the handlers can actually return, as (code, when).
    statuses: Vec<(&'static str, &'static str)>,
    /// The window a request with no `from` gets.
    window: String,
}

fn bodies(f: &mut Failures) -> Bodies {
    let text = read_or_exit(&format!("{SRC}/api.rs"));
    let lines: Vec<&str> = text.split('\n').collect();
    let fns = functions(&text);

    let mut detail = BTreeMap::new();
    for m in route_call().captures_iter(&text) {
        let route = m[1].to_string();
        let Some(h) = handler().captures(&m[2]) else {
            continue;
        };
        let name = h[2].to_string();
        let body = fns.get(&name).cloned().unwrap_or_default();
        let field = re(r#"run\(\s*"([a-z_]+)""#)
            .captures(&body)
            .map_or_else(|| "?".to_string(), |m| m[1].to_string());
        let (keys, chain) = accepted_keys(&fns, &name);
        if keys.is_empty() {
            f.fail(format!(
                "api.rs: cannot find the `known(...)` behind {route}, so the reference \
                 has no list of the keys it accepts."
            ));
        }
        // The parser is named after the handler often enough to be worth
        // guessing, and the example lives on whichever of the two carries it.
        let ex = example(&lines, &text, &chain);
        if ex.is_empty() {
            f.fail(format!(
                "api.rs: {route} has no ```yaml example in the doc comment of `{name}` \
                 or its parser. A list of key names is not a request body anyone can \
                 copy."
            ));
        }
        detail.insert(
            route,
            Detail {
                keys,
                example: ex,
                field,
                optional: body.contains("body.trim().is_empty()"),
            },
        );
    }

    let window = re(r#"time_field\(&doc\["from"\], now, now - ([\d_]+)\)"#).captures(&text);
    if window.is_none() {
        f.fail("api.rs: cannot read the default `from` out of `bounds`.");
    }
    let default_window = window.map_or_else(|| "?".to_string(), |m| nanos(&m[1]));

    // `envelope`'s format string, which is hand-written JSON: `\"blocks_total\":{}`.
    let stats: Vec<String> = re(r#"\\"([a-z_]+)\\":\{\}"#)
        .captures_iter(fns.get("envelope").map_or("", String::as_str))
        .map(|m| m[1].to_string())
        .collect();
    if stats.is_empty() {
        f.fail("api.rs: cannot read the fields of `stats` out of `envelope`.");
    }

    let mut seen: Vec<&str> = Vec::new();
    for path in glob(&format!("{SRC}/*.rs")) {
        let name = path.rsplit('/').next().unwrap_or(&path).to_string();
        if NOT_A_SURFACE.contains(&name.as_str()) {
            continue;
        }
        let src = read_or_exit(&path);
        let src = src
            .split_once("mod tests")
            .map_or(src.clone(), |(h, _)| h.to_string());
        for m in re(r"StatusCode::([A-Z_]+)").captures_iter(&src) {
            match STATUS.iter().find(|(code, _, _)| *code == &m[1]) {
                None => f.fail(format!(
                    "{name} returns StatusCode::{}, which the STATUS table in \
                     crates/xtask/src/reference.rs does not explain.",
                    &m[1]
                )),
                Some((code, _, _)) if !seen.contains(code) => seen.push(code),
                Some(_) => {}
            }
        }
    }
    let statuses = STATUS
        .iter()
        .filter(|(code, _, _)| seen.contains(code))
        .map(|(_, http, why)| (*http, *why))
        .collect();
    Bodies {
        detail,
        stats,
        statuses,
        window: default_window,
    }
}

/// The operators a term may use, and the columns a `field` term may name.
#[allow(
    clippy::type_complexity,
    reason = "two lists, read once, by one caller"
)]
fn where_terms(f: &mut Failures) -> (Vec<String>, Vec<(&'static str, Vec<(String, String)>)>) {
    let core = "crates/mira-core/src";
    let quoted = re(r#""([^"]+)""#);
    let ops: Vec<String> = re(r#"(?m)^\s+((?:"[a-z=!<>~]+"\s*\|?\s*)+)=> Op::"#)
        .captures_iter(&read_or_exit(&format!("{core}/query.rs")))
        .map(|arm| {
            quoted
                .captures_iter(&arm[1])
                .map(|m| format!("`{}`", &m[1]))
                .collect::<Vec<_>>()
                .join(" or ")
        })
        .collect();
    if ops.is_empty() {
        f.fail("query.rs: cannot read the operator list out of `Op::parse`.");
    }

    let text = read_or_exit(&format!("{core}/schema.rs"));
    let schemas: BTreeMap<&str, &str> = re(r"(?s)pub static (\w+): LazyLock<SchemaRef>.*?\n\}\);")
        .captures_iter(&text)
        .filter_map(|m| Some((m.get(1)?.as_str(), m.get(0).expect("group 0").as_str())))
        .collect();
    let field_new = re(r#"Field::new\(\s*"([a-z_]+)",\s*([A-Za-z:_0-9]+)"#);
    let mut out = Vec::new();
    for (signal, name) in SIGNAL_SCHEMA {
        let Some(body) = schemas.get(name) else {
            f.fail(format!(
                "schema.rs: no `{name}` schema, which is what `signal: {signal}` reads."
            ));
            continue;
        };
        let cols = field_new
            .captures_iter(body)
            .filter_map(|m| {
                let ty = COMPARABLE.iter().find(|(k, _)| *k == &m[2])?.1;
                Some((m[1].to_string(), ty.to_string()))
            })
            .collect();
        out.push((signal, cols));
    }
    (ops, out)
}

fn http_page(f: &mut Failures) -> String {
    let found = routes(f);
    let listed: Vec<&str> = GROUPS
        .iter()
        .flat_map(|(_, rs)| rs.iter().copied())
        .collect();
    for route in found.keys() {
        if !listed.contains(&route.as_str()) {
            f.fail(format!(
                "{route} is registered but not in the GROUPS table in \
                 crates/xtask/src/reference.rs. Add it to the group a reader would \
                 look under — an endpoint that exists and is not documented is the \
                 drift this exists for."
            ));
        }
    }
    for route in &listed {
        if !found.contains_key(*route) {
            f.fail(format!(
                "GROUPS lists {route}, which no router registers any more."
            ));
        }
    }
    if !f.is_empty() {
        // Every table below indexes into `found`; a missing route would panic
        // rather than print the message just collected.
        return String::new();
    }

    let mut out: Vec<String> = vec![
        STAMP.into(),
        String::new(),
        "# HTTP API".into(),
        String::new(),
        "**For:** anyone writing a client, a script or an agent against a running node.".into(),
        String::new(),
        "One port serves all of it (`listen.http`, 4318 by default). OTLP/gRPC is".into(),
        "a separate port (`listen.grpc`, 4317) and a separate protocol, so it is".into(),
        "not in this table.".into(),
        String::new(),
        "Request and response bodies are KYAML, of which JSON is a subset — so an".into(),
        "ordinary JSON client needs nothing special, and `content-type` is not".into(),
        "load-bearing.".into(),
        String::new(),
    ];

    // `main.rs` is the crate root, not a module, so its items are one level up
    // from every other file's.
    let modlink = |m: &str| {
        let tail = if m == "main" {
            "mira/index.html".to_string()
        } else {
            format!("mira/{m}/index.html")
        };
        format!("[`{m}`]({RUSTDOC}/{tail})")
    };

    // One sentence for the whole page rather than the same sentence under every
    // table: five near-identical "implementation is over there" lines read as
    // boilerplate, and a reader who wants the source wants the whole mapping at
    // once anyway.
    let mapping: Vec<String> = GROUPS
        .iter()
        .map(|(title, paths)| {
            let mods: std::collections::BTreeSet<&str> =
                paths.iter().map(|p| found[*p].1.as_str()).collect();
            format!(
                "**{title}** is {}",
                mods.into_iter()
                    .map(modlink)
                    .collect::<Vec<_>>()
                    .join(" and ")
            )
        })
        .collect();
    out.push("Each group below is a module, and its rustdoc is the reasoning behind".into());
    out.push("those routes rather than a restatement of this table:".into());
    let (last, head) = mapping.split_last().expect("GROUPS is not empty");
    out.extend(head.iter().map(|m| format!("{m};")));
    out.push(format!("{last}."));
    out.push(String::new());

    for (title, paths) in GROUPS {
        out.push(format!("## {title}"));
        out.push(String::new());
        out.push("| Endpoint | What it answers |".into());
        out.push("| --- | --- |".into());
        for p in paths {
            let (method, _, summary) = &found[*p];
            out.push(format!("| `{method} {p}` | {summary} |"));
        }
        out.push(String::new());
    }

    let Bodies {
        detail,
        stats,
        statuses,
        window,
    } = bodies(f);
    out.extend([
        "## Request bodies".into(),
        String::new(),
        "Every query endpoint takes a KYAML document and enforces a closed key".into(),
        "set: an unknown key is a 400 naming it, rather than a filter that was".into(),
        "silently not applied.".into(),
        String::new(),
        "`from` and `to` are each one of three things: `\"now\"`, a signed duration".into(),
        "relative to now (`\"-15m\"`, `\"+2h\"`), or Unix nanoseconds as a number.".into(),
        format!("Left out, the window is the last `{window}` ending now."),
        String::new(),
    ]);
    for (_, paths) in GROUPS {
        for p in paths {
            let Some(d) = detail.get(*p) else { continue };
            let (method, _, summary) = &found[*p];
            out.extend([
                format!("### `{method} {p}`"),
                String::new(),
                summary.clone(),
                String::new(),
            ]);
            out.push(format!(
                "Accepts {}.",
                d.keys
                    .iter()
                    .map(|k| format!("`{k}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            if d.optional {
                out.push(format!(
                    "An empty body is valid, and means the last `{window}`."
                ));
            }
            out.push(String::new());
            out.push("```yaml".into());
            out.extend(d.example[1..d.example.len() - 1].iter().cloned());
            out.push("```".into());
            out.push(String::new());
            out.push(format!(
                "Answers under `{}`, with the envelope below.",
                d.field
            ));
            out.push(String::new());
        }
    }

    let (ops, schemas) = where_terms(f);
    out.extend([
        "## `where` terms".into(),
        String::new(),
        "A term names its target and its operator in two keys rather than three:".into(),
        "`{\"attr\": \"service.name\", \"eq\": \"checkout\"}`, not a `target`/`op`/`value`".into(),
        "triple. Terms in a list are ANDed; there is no `or`.".into(),
        String::new(),
        "* `attr` — an OTLP attribute key, on the record, its scope or its".into(),
        "  resource. Any key at all; nothing is declared in advance.".into(),
        "* `field` — a column of the signal itself, from the tables below.".into(),
        String::new(),
        format!("Operators: {}.", ops.join(", ")),
        String::new(),
    ]);
    for (signal, cols) in schemas {
        out.extend([
            format!("`field` names for `signal: {signal}`:"),
            String::new(),
            "| Field | Compare against |".into(),
            "| --- | --- |".into(),
        ]);
        out.extend(cols.iter().map(|(c, t)| format!("| `{c}` | {t} |")));
        out.push(String::new());
    }

    out.extend([
        "## The response envelope".into(),
        String::new(),
        "Every query answers with its own field plus one `stats` object, so a".into(),
        "caller always learns what the read cost:".into(),
        String::new(),
        "```yaml".into(),
        "{".into(),
        "  \"rows\": [ ... ],           # or series, names, frame, map, entities".into(),
        "  \"stats\": {".into(),
    ]);
    out.extend(stats.iter().map(|s| format!("    \"{s}\": 0,")));
    out.extend([
        "  },".into(),
        "  \"next\": \"...\",             # absent on the last page".into(),
        "}".into(),
        "```".into(),
        String::new(),
        "`elapsed_us` is wall time including the wait for a scan permit — the".into(),
        "number the caller actually waited. `next` is absent rather than null when".into(),
        "there is no page behind this one, so `if (doc.next)` is the whole of a".into(),
        "reader's paging logic; pass it back as `after`.".into(),
        String::new(),
        "## Status codes".into(),
        String::new(),
        "| Code | When |".into(),
        "| --- | --- |".into(),
    ]);
    out.extend(
        statuses
            .iter()
            .map(|(code, why)| format!("| `{code}` | {why} |")),
    );
    format!("{}\n", out.join("\n").trim_end())
}

// ---------------------------------------------------------------------------
// The configuration surface
// ---------------------------------------------------------------------------

/// When the Rust type is ambiguous, the parser the arm calls is not.
const PARSED: [(&str, &str); 2] = [("positive", "count"), ("whole", "count")];

/// How a Rust type reads to an operator writing KYAML.
const TYPES: [(&str, &str); 8] = [
    ("String", "string"),
    ("SocketAddr", "host:port"),
    ("PathBuf", "path"),
    ("Option<PathBuf>", "path"),
    // The only optional string is `storage.offload`, and what it holds is a
    // URI. If a second one ever wants a different word, this is the line that
    // has to become a per-field override.
    ("Option<String>", "uri"),
    ("Duration", "duration"),
    ("usize", "size"),
    ("bool", "boolean"),
];

/// A Rust default expression as the operator would write it in KYAML.
fn humanize(expr: &str) -> String {
    let expr = expr.trim();
    for pattern in [
        r#"^"(.*)"(?:\.into\(\))?$"#,
        r#"^PathBuf::from\("(.*)"\)$"#,
        r#"^"(.*)"\.parse\(\)\.unwrap\(\)$"#,
    ] {
        if let Some(m) = re(pattern).captures(expr) {
            return m[1].to_string();
        }
    }
    if let Some(m) = re(r"^Duration::from_secs\(([\d\s*+]+)\)$").captures(expr) {
        // Sums of products, which is every spelling in `config.rs`
        // (`60 * 60`, `24 * 60 * 60`). Nothing here needs precedence beyond
        // that, and a real expression parser for four call sites would be the
        // tail wagging the dog.
        let secs: u64 = m[1]
            .split('+')
            .map(|term| {
                term.split('*')
                    .filter_map(|n| n.trim().parse::<u64>().ok())
                    .product::<u64>()
            })
            .sum();
        for (unit, n) in [("d", 86400), ("h", 3600), ("m", 60)] {
            if secs % n == 0 {
                return format!("{}{unit}", secs / n);
            }
        }
        return format!("{secs}s");
    }
    if let Some(m) = re(r"^(\d+) << (\d+)$").captures(expr) {
        let n: u64 = m[1].parse().unwrap_or_default();
        let shift: u32 = m[2].parse().unwrap_or_default();
        return match shift {
            10 => format!("{n}KiB"),
            20 => format!("{n}MiB"),
            30 => format!("{n}GiB"),
            _ => (n << shift).to_string(),
        };
    }
    if expr == "None" {
        return "unset".into();
    }
    expr.to_string()
}

/// `KNOWN` is the closed set the parser accepts, in the order it reads them,
/// and each key is set from exactly one `cfg.<field> = ...` a few lines below
/// its `get(&root, "<key>", env)`. Both facts come out of the same file, so the
/// table cannot list a key the binary would refuse.
fn key_setter() -> Regex {
    re(
        r#"(?m)get\(&root,\s*"([^"]+)",\s*env\)\?\s*\{\s*\n\s*cfg\.([a-z_]+)\s*=\s*\n?\s*([A-Za-z_]*)"#,
    )
}

/// How many keys the parser accepts, which is what `KNOWN` declares.
///
/// The opening sentence of `docs/config.md` counts them, and a count in prose is
/// the first thing to go stale when a key is added — this one cannot, because it
/// is the same array length the parser refuses everything else against.
fn known_keys(f: &mut Failures) -> usize {
    let text = read_or_exit(&format!("{SRC}/config.rs"));
    match re(r"const KNOWN: \[&str; (\d+)\]").captures(&text) {
        Some(m) => m[1].parse().unwrap_or_default(),
        None => {
            f.fail("config.rs: cannot find `KNOWN`'s length.");
            0
        }
    }
}

fn config_table(f: &mut Failures) -> String {
    let text = read_or_exit(&format!("{SRC}/config.rs"));
    let lines: Vec<&str> = text.split('\n').collect();
    let Some(known) = re(r"(?s)const KNOWN: \[&str; \d+\] = \[(.*?)\];").captures(&text) else {
        f.fail("config.rs: cannot find `KNOWN`, which is the list this table is.");
        return String::new();
    };
    let keys: Vec<String> = re(r#""([^"]+)""#)
        .captures_iter(&known[1])
        .map(|m| m[1].to_string())
        .collect();

    let mut setters: BTreeMap<String, String> = BTreeMap::new();
    // Three `usize` keys mean three different things, and the Rust type cannot
    // say which: `max_request_bytes` is bytes, `queue` is slots and `shards` is
    // tasks. The parser the arm calls can, so it is the one asked.
    let mut parsed: BTreeMap<String, String> = BTreeMap::new();
    for m in key_setter().captures_iter(&text) {
        setters.insert(m[1].to_string(), m[2].to_string());
        parsed.insert(m[2].to_string(), m[3].to_string());
    }

    let field = re(r"(?m)^\s{4}pub ([a-z_]+): ([^,]+),$");
    let types: BTreeMap<String, String> = field
        .captures_iter(&text)
        .map(|m| (m[1].to_string(), m[2].trim().to_string()))
        .collect();
    let defaults: BTreeMap<String, String> = re(r"(?m)^\s{12}([a-z_]+): (.+),$")
        .captures_iter(&text)
        .map(|m| (m[1].to_string(), humanize(&m[2])))
        .collect();
    let docs: BTreeMap<String, String> = field
        .captures_iter(&text)
        .map(|m| {
            let i = line_index(&text, m.get(0).expect("group 0").start());
            (m[1].to_string(), first_paragraph(&doc_above(&lines, i)))
        })
        .collect();

    // The same field, reached from the command line. `main.rs` writes one match
    // arm per flag, so the pairing is as readable here as it is to a reviewer.
    let flags: BTreeMap<String, String> = re(r#""(--[a-z-]+)" => cfg\.([a-z_]+)"#)
        .captures_iter(&read_or_exit(&format!("{SRC}/main.rs")))
        .map(|m| (m[2].to_string(), m[1].to_string()))
        .collect();

    let mut rows = vec![
        "| Key | Flag | Type | Default | What it sets |".to_string(),
        "| --- | --- | --- | --- | --- |".to_string(),
    ];
    for key in keys {
        let Some(fieldname) = setters.get(&key) else {
            f.fail(format!(
                "config.rs: `{key}` is in KNOWN but nothing assigns a field from it."
            ));
            continue;
        };
        let doc = docs.get(fieldname).cloned().unwrap_or_default();
        if doc.is_empty() {
            f.fail(format!(
                "config.rs: `Config::{fieldname}` has no doc comment, so `{key}` has \
                 nothing to say for itself in the table."
            ));
        }
        let ty = PARSED
            .iter()
            .find(|(p, _)| Some(*p) == parsed.get(fieldname).map(String::as_str))
            .map(|(_, t)| *t)
            .or_else(|| {
                let rust = types.get(fieldname)?;
                TYPES.iter().find(|(k, _)| k == rust).map(|(_, t)| *t)
            })
            .unwrap_or("?");
        rows.push(format!(
            "| [`{key}`]({RUSTDOC}/mira/config/struct.Config.html#structfield.{fieldname}) \
             | `{}` | {ty} | `{}` | {doc} |",
            flags.get(fieldname).map_or("—", String::as_str),
            defaults.get(fieldname).map_or("?", String::as_str),
        ));
    }
    rows.join("\n")
}

// ---------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------

fn write(rel: &str, body: &str) -> bool {
    // An empty body means the source could not be read and `fail` has already
    // said so. Truncating the page on top of that turns one clear error into a
    // deleted reference page nobody asked to delete.
    if body.trim().is_empty() {
        return false;
    }
    let path = root().join(rel);
    if let Some(dir) = path.parent() {
        let _ = std::fs::create_dir_all(dir);
    }
    if std::fs::read_to_string(&path).is_ok_and(|old| old == body) {
        return false;
    }
    if let Err(e) = std::fs::write(&path, body) {
        eprintln!("error: {rel}: {e}");
        return false;
    }
    println!("wrote {rel}");
    true
}

/// Replace one marked region of a hand-written page.
///
/// Whole-file generation would cost the prose around the table, and prose is the
/// half a generator cannot write: *why* a key exists, what it trades. So the
/// generated part is bracketed and the rest is nobody's business but the
/// author's.
pub(crate) fn inject(rel: &str, name: &str, body: &str, f: &mut Failures) -> bool {
    if body.trim().is_empty() {
        return false;
    }
    let path = root().join(rel);
    let text = read_or_exit(rel);
    let begin = format!("<!-- BEGIN GENERATED: {name} -->");
    let end = format!("<!-- END GENERATED: {name} -->");
    let (Some((head, rest)), true) = (text.split_once(&begin), text.contains(&end)) else {
        f.fail(format!(
            "{rel} has no `{begin}` / `{end}` markers for the generated block."
        ));
        return false;
    };
    let tail = rest.split_once(&end).expect("checked above").1;
    let new = format!("{head}{begin}\n{body}\n{end}{tail}");
    if new == text {
        return false;
    }
    if let Err(e) = std::fs::write(&path, new) {
        eprintln!("error: {rel}: {e}");
        return false;
    }
    println!("wrote {rel} ({name})");
    true
}

fn cli_page(f: &mut Failures) -> String {
    let bin = root().join("target/release/mira");
    if !bin.exists() {
        f.fail("target/release/mira is not built. Run `make build` first.");
        return String::new();
    }
    let out = match Command::new(&bin).arg("--help").output() {
        Ok(out) if out.status.success() => out.stdout,
        Ok(out) => {
            f.fail(format!("`mira --help` exited {}", out.status));
            return String::new();
        }
        Err(e) => {
            f.fail(format!("`mira --help`: {e}"));
            return String::new();
        }
    };
    let help = String::from_utf8_lossy(&out).trim_end().to_string();
    let page = [
        STAMP,
        "",
        "# CLI",
        "",
        "**For:** anyone starting the binary.",
        "",
        "One binary. `mira` is the server, `mira mira` is the terminal UI",
        "over the same blocks, `mira update` replaces the binary — and there",
        "is no daemon, agent or sidecar to run alongside any of them.",
        "",
        "```console",
        "$ mira --help",
        &help,
        "```",
        // The help text above already states the precedence rule, so this
        // closing line points at the page that expands it rather than saying
        // the same sentence a second line down.
        "",
        "Every flag on the server line is also a config-file key:",
        "[Configuration](../config.md) is the table, with the type, the",
        "default and what each one sets. Four here are not, because there is",
        "nothing for them to persist: `--config` names the file itself,",
        "`--version` exits, and `--addr` and `--dry-run` belong to `mira mira`",
        "and `mira update` rather than to the server. The config file is a",
        "closed set, so writing one of them into it is an `unknown key` at",
        "boot rather than a setting that is quietly ignored.",
        "",
    ]
    .join("\n");
    format!("{}\n", page.trim_end())
}

/// Every `miradb.dev/api/...` link resolves to a page rustdoc actually built.
///
/// These links are the join between the prose and the generated API docs, and
/// they are the one part of it a generator cannot get right by construction: a
/// renamed module or a field that becomes private leaves a 404 behind that
/// nothing else notices. `target/doc` is the same tree that gets published, so
/// checking against it here is checking against what the reader will get.
///
/// Only when it is built — `make reference` is run on its own during
/// development, and requiring a full rustdoc build for a table of routes would
/// make the fast gate the slow one. `make site` builds it, and so does CI.
fn check_rustdoc_links(f: &mut Failures) {
    let doc = root().join("target/doc");
    if !doc.join("mira/index.html").exists() {
        println!("note: target/doc is not built; skipped the rustdoc link check.");
        return;
    }
    // Every markdown file, not just the generated ones: the architecture pages
    // hand the reader off to rustdoc by module, and a rename there is exactly
    // the drift this exists to catch.
    let mut pages = glob("docs/**/*.md");
    pages.push("README.md".into());
    // `[^\s)]+` rather than a lookahead for `)` or whitespace: a URL contains
    // neither, so greedy-up-to-them is the same language without needing an
    // engine that backtracks.
    let link = re(&format!(r"{}([^\s)]+)", regex::escape(RUSTDOC)));
    for rel in pages {
        let text = read_or_exit(&rel);
        for m in link.captures_iter(&text) {
            let url = &m[1];
            let page = doc.join(url.split('#').next().unwrap_or(url).trim_start_matches('/'));
            if !page.exists() {
                f.fail(format!(
                    "{rel} links to {url}, which rustdoc did not build."
                ));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The one transformation between a Rust doc comment and a Markdown table
    /// cell. Get it wrong and every row carries a dangling reference-style link.
    #[test]
    fn a_summary_strips_intra_doc_brackets_but_not_real_links() {
        let doc = |s: &str| vec![s.to_string()];
        assert_eq!(
            first_paragraph(&doc("Set by [`Config::wal`].")),
            "Set by `Config::wal`."
        );
        assert_eq!(
            first_paragraph(&doc("See [`here`](x.md).")),
            "See [`here`](x.md)."
        );
        // Everything up to the first blank line, and no further.
        let multi = ["One".into(), "two.".into(), String::new(), "Later.".into()];
        assert_eq!(first_paragraph(&multi), "One two.");
    }

    /// `#[attr]` between the comment and the item is the case that silently
    /// produced blank table cells before it was handled.
    #[test]
    fn a_doc_comment_is_read_through_an_attribute() {
        let src = "/// What it is.\n///\n/// More.\n#[serde(skip)]\npub field: u8,\n";
        let lines: Vec<&str> = src.split('\n').collect();
        assert_eq!(
            doc_above(&lines, 4),
            vec!["What it is.".to_string(), String::new(), "More.".into()]
        );
    }

    /// Default expressions, as the operator reads them rather than as Rust.
    #[test]
    fn a_default_reads_as_the_value_an_operator_would_write() {
        for (expr, want) in [
            (r#""mira".into()"#, "mira"),
            (r#"PathBuf::from("./data")"#, "./data"),
            (r#""0.0.0.0:4318".parse().unwrap()"#, "0.0.0.0:4318"),
            ("Duration::from_secs(60)", "1m"),
            ("Duration::from_secs(24 * 60 * 60)", "1d"),
            ("Duration::from_secs(90)", "90s"),
            ("4 << 20", "4MiB"),
            ("None", "unset"),
            ("true", "true"),
        ] {
            assert_eq!(humanize(expr), want, "{expr}");
        }
    }

    #[test]
    fn a_nanosecond_literal_reads_as_a_duration() {
        assert_eq!(nanos("3_600_000_000_000"), "1h");
        assert_eq!(nanos("90_000_000_000"), "90s");
    }

    /// The generator, run against the tree it generates from. This is
    /// `make reference-check` minus the `git diff`: if the code cannot be read,
    /// it fails here rather than six minutes into CI.
    #[test]
    fn every_page_can_be_generated_from_this_tree() {
        let mut f = Failures::default();
        let http = http_page(&mut f);
        let config = config_table(&mut f);
        assert!(f.0.is_empty(), "{:?}", f.0);
        assert!(http.contains("| `POST /api/v1/query` |"), "{http}");
        assert!(config.contains("[`listen.http`]"), "{config}");
        assert!(known_keys(&mut f) > 0);
    }
}
