//! Emit the `MiraCluster` CRD as YAML on stdout.
//!
//! The chart's CRD file is generated by this and never edited by hand, the same
//! way `docs/reference/cli.md` is generated in the engine's tree. `make crd`
//! writes it and CI re-runs the generator and diffs — so a field added to the
//! struct without regenerating is a red build rather than a schema that
//! silently rejects the field it documents.

fn main() {
    let crd = <mira_operator::crd::MiraCluster as kube::CustomResourceExt>::crd();
    print!(
        "# Generated by `cargo run --bin crdgen`. Do not edit.\n{}",
        serde_yaml_ng::to_string(&crd).expect("a derived CRD serialises")
    );
}
