[package]
name = "mira"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Mira: an OTLP-native telemetry storage engine in a single binary"

[[bin]]
name = "mira"
path = "src/main.rs"

[dependencies]
mira-core.workspace = true
mira-proto.workspace = true
arrow-array.workspace = true
prost.workspace = true
tonic.workspace = true
tonic-types = "0.14"
axum.workspace = true
tokio.workspace = true
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
yaml-rust2 = { version = "0.12.0", default-features = false }

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
