#!/usr/bin/env python3
"""Generate the reference pages, so that nobody maintains them by hand.

A reference page is a list of things the code already knows: the flags the
binary prints, the routes the router registers, the keys the config parser
reads. Written by hand, every one of them is a promise that decays the first
time someone adds a route and does not think of the docs. Nobody notices,
because a docs page cannot fail a test.

So the code is the source and these pages are the output:

  docs/reference/cli.md    <- `mira --help`, verbatim, from the built binary
  docs/reference/http.md   <- `.route(...)` calls + the handler's doc comment
  docs/config.md           <- the `KNOWN` key list + `Config`'s field docs,
                              injected between markers so the prose survives

`make reference` writes them; `make reference-check` writes them and then
`git diff --exit-code`s, which is what CI runs. That is the same shape as the
committed UI bundle and the generated chart README: the artefact is in git so a
reader gets it without a build, and a pull request that changes the code
without regenerating goes red.

Descriptions come from doc comments, which is the second half of the point:
rustdoc publishes the *whole* comment at miradb.dev/api/, this takes the first
paragraph of the same comment for the summary table, and there is one text to
keep true rather than two.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "crates/mira/src"
BIN = ROOT / "target/release/mira"

# Where the rustdoc for a symbol lives once `make site` has published it. The
# summary tables link into it, so "the rest of the comment" is one click from
# every row rather than a file path a reader has to go and clone.
RUSTDOC = "https://miradb.dev/api"

STAMP = (
    "<!-- Generated by scripts/gen_reference.py from the code it documents.\n"
    "     Do not edit: run `make reference`. -->"
)

# ---------------------------------------------------------------------------
# Reading Rust
# ---------------------------------------------------------------------------

# A doc comment is the run of `///` lines immediately above an item. Rust has
# no other place to put one, so this is the whole grammar.
DOC_LINE = re.compile(r"^\s*///(.*)$")


def doc_above(lines: list[str], i: int) -> list[str]:
    """The `///` block ending at line `i - 1`, outermost line first."""
    out = []
    j = i - 1
    while j >= 0:
        m = DOC_LINE.match(lines[j])
        if not m:
            # `#[attr]` sits between the doc comment and the item it documents.
            if lines[j].lstrip().startswith("#["):
                j -= 1
                continue
            break
        out.append(m.group(1).strip())
        j -= 1
    return list(reversed(out))


# `[`Config::wal`]` is a rustdoc intra-doc link, and markdown reads it as a
# reference-style link to a definition that does not exist on the page. The
# brackets come off; the code span stays.
INTRA_DOC = re.compile(r"\[(`[^`]+`)\](?!\()")


def first_paragraph(doc: list[str]) -> str:
    """The summary sentence: everything up to the first blank line, joined."""
    para = []
    for line in doc:
        if not line:
            break
        para.append(line)
    return INTRA_DOC.sub(r"\1", " ".join(para).strip())


def comment_above(lines: list[str], i: int) -> str:
    """The `//` block ending at line `i - 1`, for the routes a macro builds.

    A macro expansion is not an item, so it cannot carry a doc comment and
    rustdoc will never see it. The three OTLP export routes are the whole of
    that case; an ordinary comment above the `.route(` line is where their
    description lives, and the generator says so out loud rather than silently
    emitting a blank cell.
    """
    out = []
    j = i - 1
    while j >= 0 and lines[j].lstrip().startswith("//") and not lines[j].lstrip().startswith("///"):
        out.append(lines[j].lstrip()[2:].strip())
        j -= 1
    return " ".join(reversed(out)).strip()


# ---------------------------------------------------------------------------
# The HTTP surface
# ---------------------------------------------------------------------------

ROUTE = re.compile(r"\.route\(\s*\n?\s*\"([^\"]+)\"\s*,\s*([^\n]*)")
HANDLER = re.compile(r"(?:axum::routing::)?(get|post)\(\s*([A-Za-z_][A-Za-z0-9_]*)")
MACRO_CALL = re.compile(r"([a-z_]+)!\(")

# The body half of the surface, which is the half a table of paths and
# one-liners leaves out. All four facts below are already written down in code —
# the parser's closed key set, the example in its doc comment, the name the
# results come back under, the fields of `stats` — so they belong here for the
# same reason the paths do.
FN = re.compile(r"^(?:pub(?:\([a-z:]+\))? )?(?:async )?fn ([a-z_][a-z0-9_]*)", re.M)
KNOWN_CALL = re.compile(r"known\(\s*(?:&?doc|y)\s*,\s*&\[([^\]]*)\]", re.S)
RUN_FIELD = re.compile(r'run\(\s*"([a-z_]+)"')
CALLS = re.compile(r"\b([a-z_][a-z0-9_]*)\s*\(")
# `envelope`'s format string, which is hand-written JSON: `\"blocks_total\":{}`.
STAT = re.compile(r'\\"([a-z_]+)\\":\{\}')

# What each status the handlers emit means to a caller. Keyed on the Rust
# constant, so a new one added to a handler lands here as a failure rather than
# as a table that quietly stops being the whole list.
STATUS = {
    "OK": ("200", "The answer, as the envelope below."),
    "BAD_REQUEST": (
        "400",
        "The document did not parse, named a key no endpoint accepts, or gave a "
        "value out of range. The body is `{\"error\": \"...\"}` — JSON, like the "
        "success, so a caller has one thing to parse.",
    ),
    "INTERNAL_SERVER_ERROR": (
        "500",
        "The read failed or its thread panicked. The body is the error text.",
    ),
    "PAYLOAD_TOO_LARGE": (
        "413",
        "The export was larger than `ingest.max_request_bytes`.",
    ),
    "SERVICE_UNAVAILABLE": (
        "503",
        "The signal's queue is full and the export was shed. Retry it: this is "
        "backpressure, not a failure, and `ingest.queue` is how much of it an "
        "operator buys away.",
    ),
    "UNSUPPORTED_MEDIA_TYPE": ("415", "The export was not protobuf."),
    "ACCEPTED": (
        "202",
        "An OTLP export was queued, or an MCP notification was taken. Accepted "
        "means durable when `ingest.wal` is on and queued when it is off.",
    ),
    "NOT_MODIFIED": ("304", "A UI asset the caller already has. The bundle is "
                     "built into the binary, so its ETag is its content hash."),
    "NOT_FOUND": ("404", "No such UI asset."),
}

# A `where` term's two halves, both closed sets the code already holds: the
# operators `Op::parse` accepts, and the columns a `field` term can name.
OP_ARM = re.compile(r'^\s+((?:"[a-z=!<>~]+"\s*\|?\s*)+)=> Op::', re.M)
SCHEMA = re.compile(r"pub static (\w+): LazyLock<SchemaRef>.*?\n\}\);", re.S)
FIELD_NEW = re.compile(r'Field::new\(\s*"([a-z_]+)",\s*([A-Za-z:_0-9]+)')

# An Arrow type as "what may I compare this against". Anything not here is a
# column no term can usefully match, and is left out of the table rather than
# listed with a type a caller cannot write in KYAML.
COMPARABLE = {
    "DataType::Utf8": "string",
    "dict_u16_utf8": "string",
    "DataType::Int32": "number",
    "DataType::Int64": "number",
    "DataType::UInt8": "number",
    "DataType::UInt16": "number",
    "DataType::UInt32": "number",
    "DataType::UInt64": "number",
    "DataType::Float64": "number",
    "DataType::Boolean": "boolean",
    "ts": "nanoseconds",
    "DataType::FixedSizeBinary": "hex string",
}

# Which root schema each `signal` value queries. `Signal::parse` maps the name
# and `search_open` reads the root batch, so these two are the whole of what a
# `field` term can name.
SIGNAL_SCHEMA = [("logs", "LOGS"), ("traces", "SPANS")]

# `e2e.rs` is the in-process end-to-end suite, not a surface. The statuses in it
# are the ones it asserts on, and listing them here would document the tests.
NOT_A_SURFACE = {"e2e.rs"}


def functions(text: str) -> dict[str, str]:
    """Every free function in a file, name -> body text.

    A body ends at the first line that is a bare `}`, which is true of every
    function in this tree because rustfmt puts it there.
    """
    lines = text.split("\n")
    out: dict[str, str] = {}
    for m in FN.finditer(text):
        i = text[: m.start()].count("\n")
        j = i + 1
        while j < len(lines) and lines[j] != "}":
            j += 1
        out[m.group(1)] = "\n".join(lines[i:j])
    return out


def accepted_keys(fns: dict[str, str], entry: str) -> tuple[list[str], list[str]]:
    """The closed key set a handler's parser enforces, found transitively.

    A handler calls `parse_search`, which calls `search_doc`, which is where the
    `known(...)` is. Following the calls is what makes this survive someone
    moving the check one function further down. The walk order comes back too:
    it is also where the example belongs, and guessing the parser's name from
    the handler's only works until one of them is renamed.
    """
    seen, order, queue = set(), [], [entry]
    while queue:
        name = queue.pop(0)
        if name in seen or name not in fns:
            continue
        seen.add(name)
        order.append(name)
        body = fns[name]
        if m := KNOWN_CALL.search(body):
            return re.findall(r'"([^"]+)"', m.group(1)), order
        queue += CALLS.findall(body)
    return [], order


def example(lines: list[str], text: str, names: list[str]) -> list[str]:
    """The ```yaml block from the first of `names` whose doc comment has one.

    Read off the raw lines rather than through [`doc_above`], which strips each
    one: the indentation inside a fenced block is the example, and a request
    body flattened to column zero is one a reader has to re-format before it
    reads as the nested document it is.
    """
    for name in names:
        fn = re.search(rf"^(?:pub(?:\([a-z:]+\))? )?(?:async )?fn {re.escape(name)}\b", text, re.M)
        if not fn:
            continue
        out, j = [], text[: fn.start()].count("\n") - 1
        while j >= 0 and (m := DOC_LINE.match(lines[j])):
            out.append(m.group(1)[1:] if m.group(1).startswith(" ") else m.group(1))
            j -= 1
        out.reverse()
        if "```yaml" in out:
            i = out.index("```yaml")
            return out[i : out.index("```", i + 1) + 1]
    return []

# Routes are grouped the way a reader meets them, not the way the files happen
# to sort. The port is part of the answer: everything below is on `listen.http`
# except the gRPC service, which is not a route at all.
GROUPS = [
    ("Ingest", ["/v1/logs", "/v1/traces", "/v1/metrics"]),
    (
        "Query",
        [
            "/api/v1/query",
            "/api/v1/metrics/query",
            "/api/v1/metrics/names",
            "/api/v1/correlate",
            "/api/v1/map",
            "/api/v1/entities",
        ],
    ),
    ("Agents", ["/mcp"]),
    ("Operate", ["/health", "/readyz", "/api/v1/stats", "/api/v1/alerts"]),
    ("Web UI", ["/", "/{file}"]),
]


def routes() -> dict[str, tuple[str, str, str]]:
    """Every registered route: path -> (method, module, summary)."""
    found: dict[str, tuple[str, str, str]] = {}
    for path in sorted(SRC.glob("*.rs")):
        text = path.read_text()
        lines = text.split("\n")
        # Line numbers for the offsets the regex reports, so a match can look
        # upwards for the comment that describes it.
        starts = []
        n = 0
        for line in lines:
            starts.append(n)
            n += len(line) + 1

        for m in ROUTE.finditer(text):
            route, rest = m.group(1), m.group(2)
            i = next(k for k in range(len(starts) - 1, -1, -1) if starts[k] <= m.start())
            h = HANDLER.search(rest)
            if h:
                method, name = h.group(1).upper(), h.group(2)
                # The handler's own doc comment, wherever it is in this file.
                fn = re.search(rf"^(?:async )?fn {re.escape(name)}\b", text, re.M)
                summary = ""
                if fn:
                    k = text[: fn.start()].count("\n")
                    summary = first_paragraph(doc_above(lines, k))
                if not summary:
                    fail(
                        f"{path.name}: handler `{name}` for {route} has no doc "
                        "comment. The reference table takes its first paragraph, "
                        "and a route nobody can describe in one sentence is a "
                        "route nobody should be shipping."
                    )
            else:
                mac = MACRO_CALL.search(rest)
                if not mac:
                    fail(f"{path.name}: cannot read the handler of {route}: {rest!r}")
                    continue
                # `macro_rules! signal { ... => { post( ... ) } }`: the method is
                # the first routing constructor in the macro body.
                body = text.split(f"macro_rules! {mac.group(1)}", 1)[-1]
                mm = re.search(r"\b(get|post)\(", body)
                method = mm.group(1).upper() if mm else "?"
                summary = comment_above(lines, i)
                if not summary:
                    fail(
                        f"{path.name}: {route} is built by a macro, so it has no "
                        "doc comment. Put a `//` comment on the line above the "
                        "`.route(` call; that is where this table reads it."
                    )
            found[route] = (method, path.stem, summary)
    return found


def where_terms() -> tuple[list[str], list[tuple[str, list[tuple[str, str]]]]]:
    """The operators a term may use, and the columns a `field` term may name."""
    core = ROOT / "crates/mira-core/src"
    ops = []
    for arm in OP_ARM.findall((core / "query.rs").read_text()):
        spellings = re.findall(r'"([^"]+)"', arm)
        ops.append(" or ".join(f"`{x}`" for x in spellings))
    if not ops:
        fail("query.rs: cannot read the operator list out of `Op::parse`.")

    text = (core / "schema.rs").read_text()
    schemas = dict(SCHEMA.findall(text) and [(m.group(1), m.group(0)) for m in SCHEMA.finditer(text)])
    out = []
    for signal, name in SIGNAL_SCHEMA:
        if name not in schemas:
            fail(f"schema.rs: no `{name}` schema, which is what `signal: {signal}` reads.")
            continue
        cols = [
            (col, COMPARABLE[ty])
            for col, ty in FIELD_NEW.findall(schemas[name])
            if ty in COMPARABLE
        ]
        out.append((signal, cols))
    return ops, out


def nanos(literal: str) -> str:
    """`3_600_000_000_000` as the duration an operator would write."""
    n = int(literal.replace("_", "")) // 1_000_000_000
    for unit, size in (("d", 86400), ("h", 3600), ("m", 60)):
        if n % size == 0:
            return f"{n // size}{unit}"
    return f"{n}s"


def bodies() -> tuple[dict[str, dict], list[str], list[tuple[str, str]], str]:
    """Everything about a query endpoint that is not its path.

    Returns the per-route detail, the fields of the response `stats` object, the
    statuses the handlers can return, and the window they default to.
    """
    text = (SRC / "api.rs").read_text()
    lines = text.split("\n")
    fns = functions(text)

    detail: dict[str, dict] = {}
    for route, rest in ROUTE.findall(text):
        h = HANDLER.search(rest)
        if not h:
            continue
        name = h.group(2)
        body = fns.get(name, "")
        field = RUN_FIELD.search(body)
        keys, chain = accepted_keys(fns, name)
        if not keys:
            fail(
                f"api.rs: cannot find the `known(...)` behind {route}, so the "
                "reference has no list of the keys it accepts."
            )
        # The parser is named after the handler often enough to be worth
        # guessing, and the example lives on whichever of the two carries it.
        ex = example(lines, text, chain)
        if not ex:
            fail(
                f"api.rs: {route} has no ```yaml example in the doc comment of "
                f"`{name}` or its parser. A list of key names is not a request "
                "body anyone can copy."
            )
        detail[route] = {
            "keys": keys,
            "example": ex,
            "field": field.group(1) if field else "?",
            # Three endpoints answer "right now" to an empty body, and that is
            # the shortest useful request against a fresh node.
            "optional": "body.trim().is_empty()" in body,
        }

    window = re.search(r'time_field\(&doc\["from"\], now, now - ([\d_]+)\)', text)
    if not window:
        fail("api.rs: cannot read the default `from` out of `bounds`.")
    default_window = nanos(window.group(1)) if window else "?"

    stats = STAT.findall(fns.get("envelope", ""))
    if not stats:
        fail("api.rs: cannot read the fields of `stats` out of `envelope`.")

    seen = []
    for path in sorted(SRC.glob("*.rs")):
        if path.name in NOT_A_SURFACE:
            continue
        src = path.read_text().split("mod tests", 1)[0]
        for code in re.findall(r"StatusCode::([A-Z_]+)", src):
            if code not in STATUS:
                fail(
                    f"{path.name} returns StatusCode::{code}, which "
                    "gen_reference.py's STATUS table does not explain."
                )
            elif code not in seen:
                seen.append(code)
    order = list(STATUS)
    return detail, stats, [STATUS[c] for c in sorted(seen, key=order.index)], default_window


def http_page() -> str:
    found = routes()
    listed = {r for _, rs in GROUPS for r in rs}
    for route in found:
        if route not in listed:
            fail(
                f"{route} is registered but not in gen_reference.py's GROUPS. "
                "Add it to the group a reader would look under — an endpoint "
                "that exists and is not documented is the drift this script is "
                "for."
            )
    for route in listed:
        if route not in found:
            fail(f"GROUPS lists {route}, which no router registers any more.")

    out = [
        STAMP,
        "",
        "# HTTP API",
        "",
        "**For:** anyone writing a client, a script or an agent against a running node.",
        "",
        "One port serves all of it (`listen.http`, 4318 by default). OTLP/gRPC is",
        "a separate port (`listen.grpc`, 4317) and a separate protocol, so it is",
        "not in this table.",
        "",
        "Request and response bodies are KYAML, of which JSON is a subset — so an",
        "ordinary JSON client needs nothing special, and `content-type` is not",
        "load-bearing.",
        "",
    ]

    # `main.rs` is the crate root, not a module, so its items are one level up
    # from every other file's.
    def modlink(m: str) -> str:
        tail = "mira/index.html" if m == "main" else f"mira/{m}/index.html"
        return f"[`{m}`]({RUSTDOC}/{tail})"

    # One sentence for the whole page rather than the same sentence under every
    # table: five near-identical "implementation is over there" lines read as
    # boilerplate, and a reader who wants the source wants the whole mapping at
    # once anyway.
    mapping = [
        f"**{title}** is "
        + " and ".join(modlink(m) for m in sorted({found[p][1] for p in paths}))
        for title, paths in GROUPS
    ]
    out += [
        "Each group below is a module, and its rustdoc is the reasoning behind",
        "those routes rather than a restatement of this table:",
        *[f"{m};" for m in mapping[:-1]],
        f"{mapping[-1]}.",
        "",
    ]
    for title, paths in GROUPS:
        out += [f"## {title}", "", "| Endpoint | What it answers |", "| --- | --- |"]
        for p in paths:
            method, module, summary = found[p]
            out.append(f"| `{method} {p}` | {summary} |")
        out.append("")

    detail, stats, statuses, window = bodies()
    out += [
        "## Request bodies",
        "",
        "Every query endpoint takes a KYAML document and enforces a closed key",
        "set: an unknown key is a 400 naming it, rather than a filter that was",
        "silently not applied.",
        "",
        "`from` and `to` are each one of three things: `\"now\"`, a signed duration",
        f"relative to now (`\"-15m\"`, `\"+2h\"`), or Unix nanoseconds as a number.",
        f"Left out, the window is the last `{window}` ending now.",
        "",
    ]
    for title, paths in GROUPS:
        for p in paths:
            if p not in detail:
                continue
            d = detail[p]
            out += [f"### `{found[p][0]} {p}`", "", found[p][2], ""]
            out.append("Accepts " + ", ".join(f"`{k}`" for k in d["keys"]) + ".")
            if d["optional"]:
                out.append(f"An empty body is valid, and means the last `{window}`.")
            out += ["", "```yaml"] + d["example"][1:-1] + ["```", ""]
            out += [f"Answers under `{d['field']}`, with the envelope below.", ""]

    ops, schemas = where_terms()
    out += [
        "## `where` terms",
        "",
        "A term names its target and its operator in two keys rather than three:",
        "`{\"attr\": \"service.name\", \"eq\": \"checkout\"}`, not a `target`/`op`/`value`",
        "triple. Terms in a list are ANDed; there is no `or`.",
        "",
        "* `attr` — an OTLP attribute key, on the record, its scope or its",
        "  resource. Any key at all; nothing is declared in advance.",
        "* `field` — a column of the signal itself, from the tables below.",
        "",
        "Operators: " + ", ".join(ops) + ".",
        "",
    ]
    for signal, cols in schemas:
        out += [
            f"`field` names for `signal: {signal}`:",
            "",
            "| Field | Compare against |",
            "| --- | --- |",
        ]
        out += [f"| `{c}` | {t} |" for c, t in cols]
        out.append("")

    out += [
        "## The response envelope",
        "",
        "Every query answers with its own field plus one `stats` object, so a",
        "caller always learns what the read cost:",
        "",
        "```yaml",
        "{",
        '  "rows": [ ... ],           # or series, names, frame, map, entities',
        '  "stats": {',
    ]
    out += [f'    "{s}": 0,' for s in stats]
    out += [
        "  },",
        '  "next": "...",             # absent on the last page',
        "}",
        "```",
        "",
        "`elapsed_us` is wall time including the wait for a scan permit — the",
        "number the caller actually waited. `next` is absent rather than null when",
        "there is no page behind this one, so `if (doc.next)` is the whole of a",
        "reader's paging logic; pass it back as `after`.",
        "",
        "## Status codes",
        "",
        "| Code | When |",
        "| --- | --- |",
    ]
    out += [f"| `{code}` | {why} |" for code, why in statuses]
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------------
# The configuration surface
# ---------------------------------------------------------------------------

# `KNOWN` is the closed set the parser accepts, in the order it reads them, and
# each key is set from exactly one `cfg.<field> = ...` a few lines below its
# `get(&root, "<key>", env)`. Both facts come out of the same file, so the table
# below cannot list a key the binary would refuse.
KEY = re.compile(
    r'get\(&root,\s*"([^"]+)",\s*env\)\?\s*\{\s*\n\s*cfg\.([a-z_]+)\s*=\s*\n?\s*([A-Za-z_]*)',
    re.M,
)
FIELD = re.compile(r"^\s{4}pub ([a-z_]+): ([^,]+),$", re.M)
DEFAULT = re.compile(r"^\s{12}([a-z_]+): (.+),$", re.M)
# The same field, reached from the command line. `main.rs` writes one match arm
# per flag, so the pairing is as readable to this script as it is to a reviewer.
FLAG = re.compile(r'"(--[a-z-]+)" => cfg\.([a-z_]+)')

# When the Rust type is ambiguous, the parser the arm calls is not.
PARSED = {"positive": "count"}

# How a Rust type reads to an operator writing KYAML.
TYPES = {
    "String": "string",
    "SocketAddr": "host:port",
    "PathBuf": "path",
    "Option<PathBuf>": "path",
    "Duration": "duration",
    "usize": "size",
    "bool": "boolean",
}


def humanize(expr: str) -> str:
    """A Rust default expression as the operator would write it in KYAML."""
    expr = expr.strip()
    if m := re.fullmatch(r'"(.*)"(?:\.into\(\))?', expr):
        return m.group(1)
    if m := re.fullmatch(r'PathBuf::from\("(.*)"\)', expr):
        return m.group(1)
    if m := re.fullmatch(r'"(.*)"\.parse\(\)\.unwrap\(\)', expr):
        return m.group(1)
    if m := re.fullmatch(r"Duration::from_secs\(([\d\s*+]+)\)", expr):
        secs = eval(m.group(1))  # noqa: S307 - digits and `*+` only, matched above
        for unit, n in (("d", 86400), ("h", 3600), ("m", 60)):
            if secs % n == 0:
                return f"{secs // n}{unit}"
        return f"{secs}s"
    if m := re.fullmatch(r"(\d+) << (\d+)", expr):
        n, shift = int(m.group(1)), int(m.group(2))
        unit = {10: "KiB", 20: "MiB", 30: "GiB"}.get(shift)
        return f"{n}{unit}" if unit else str(n << shift)
    if expr == "None":
        return "unset"
    return expr


def known_keys() -> int:
    """How many keys the parser accepts, which is what `KNOWN` declares.

    The opening sentence of `docs/config.md` counts them, and a count in prose
    is the first thing to go stale when a key is added — this one cannot,
    because it is the same array length the parser refuses everything else
    against.
    """
    text = (SRC / "config.rs").read_text()
    m = re.search(r"const KNOWN: \[&str; (\d+)\]", text)
    if not m:
        fail("config.rs: cannot find `KNOWN`'s length.")
        return 0
    return int(m.group(1))


def config_table() -> str:
    text = (SRC / "config.rs").read_text()
    lines = text.split("\n")
    known = re.search(r"const KNOWN: \[&str; \d+\] = \[(.*?)\];", text, re.S)
    if not known:
        fail("config.rs: cannot find `KNOWN`, which is the list this table is.")
        return ""
    keys = re.findall(r'"([^"]+)"', known.group(1))
    setters = {k: f for k, f, _ in KEY.findall(text)}
    # Two `usize` keys mean two different things, and the Rust type cannot say
    # which: `max_request_bytes` is bytes and `queue` is slots. The parser the
    # arm calls can, so it is the one asked.
    parsed = {f: p for _, f, p in KEY.findall(text)}

    types = {f: t.strip() for f, t in FIELD.findall(text)}
    defaults = {f: humanize(v) for f, v in DEFAULT.findall(text)}
    docs = {}
    for m in FIELD.finditer(text):
        i = text[: m.start()].count("\n")
        docs[m.group(1)] = first_paragraph(doc_above(lines, i))

    flags = {field: flag for flag, field in FLAG.findall((SRC / "main.rs").read_text())}

    rows = [
        "| Key | Flag | Type | Default | What it sets |",
        "| --- | --- | --- | --- | --- |",
    ]
    for key in keys:
        field = setters.get(key)
        if field is None:
            fail(f"config.rs: `{key}` is in KNOWN but nothing assigns a field from it.")
            continue
        if not docs.get(field):
            fail(
                f"config.rs: `Config::{field}` has no doc comment, so `{key}` "
                "has nothing to say for itself in the table."
            )
        link = f"{RUSTDOC}/mira/config/struct.Config.html#structfield.{field}"
        rows.append(
            f"| [`{key}`]({link}) | `{flags.get(field, '—')}` "
            f"| {PARSED.get(parsed.get(field, ''), TYPES.get(types.get(field, ''), '?'))} "
            f"| `{defaults.get(field, '?')}` | {docs.get(field, '')} |"
        )
    return "\n".join(rows)


# ---------------------------------------------------------------------------
# Writing
# ---------------------------------------------------------------------------

BEGIN = "<!-- BEGIN GENERATED: {} -->"
END = "<!-- END GENERATED: {} -->"

failures: list[str] = []


def fail(msg: str) -> None:
    failures.append(msg)


def write(rel: str, body: str) -> bool:
    # An empty body means the source could not be read and `fail` has already
    # said so. Truncating the page on top of that turns one clear error into a
    # deleted reference page nobody asked to delete.
    if not body.strip():
        return False
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text() if path.exists() else None
    if old == body:
        return False
    path.write_text(body)
    print(f"wrote {rel}")
    return True


def inject(rel: str, name: str, body: str) -> bool:
    """Replace one marked region of a hand-written page.

    Whole-file generation would cost the prose around the table, and prose is
    the half a generator cannot write: *why* a key exists, what it trades. So
    the generated part is bracketed and the rest is nobody's business but the
    author's.
    """
    path = ROOT / rel
    text = path.read_text()
    begin, end = BEGIN.format(name), END.format(name)
    if begin not in text or end not in text:
        fail(f"{rel} has no `{begin}` / `{end}` markers for the generated block.")
        return False
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    new = f"{head}{begin}\n{body}\n{end}{tail}"
    if new == text:
        return False
    path.write_text(new)
    print(f"wrote {rel} ({name})")
    return True


def cli_page() -> str:
    if not BIN.exists():
        fail(f"{BIN.relative_to(ROOT)} is not built. Run `make build` first.")
        return ""
    help_text = subprocess.run(
        [str(BIN), "--help"], capture_output=True, text=True, check=True
    ).stdout.rstrip()
    return "\n".join(
        [
            STAMP,
            "",
            "# CLI",
            "",
            "**For:** anyone starting the binary.",
            "",
            "One binary. `mira` is the server, `mira mira` is the terminal UI",
            "over the same blocks, `mira update` replaces the binary — and there",
            "is no daemon, agent or sidecar to run alongside any of them.",
            "",
            "```console",
            "$ mira --help",
            help_text,
            "```",
            # The help text above already states the precedence rule, so this
            # closing line points at the page that expands it rather than
            # saying the same sentence a second line down.
            "",
            "Every flag here is also a config-file key:",
            "[Configuration](../config.md) is the table, with the type, the",
            "default and what each one sets.",
            "",
        ]
    ).rstrip() + "\n"


def check_rustdoc_links() -> None:
    """Every `miradb.dev/api/...` link resolves to a page rustdoc actually built.

    These links are the join between the prose and the generated API docs, and
    they are the one part of it a generator cannot get right by construction: a
    renamed module or a field that becomes private leaves a 404 behind that
    nothing else notices. `target/doc` is the same tree that gets published, so
    checking against it here is checking against what the reader will get.

    Only when it is built — `make reference` is run on its own during
    development, and requiring a full rustdoc build for a table of routes would
    make the fast gate the slow one. `make site` builds it, and so does CI.
    """
    doc = ROOT / "target/doc"
    if not (doc / "mira/index.html").exists():
        print("note: target/doc is not built; skipped the rustdoc link check.")
        return
    # Every markdown file, not just the generated ones: the architecture pages
    # hand the reader off to rustdoc by module, and a rename there is exactly the
    # drift this exists to catch.
    pages = sorted(ROOT.glob("docs/**/*.md")) + [ROOT / "README.md"]
    for path in pages:
        rel = path.relative_to(ROOT)
        for url in re.findall(rf"{re.escape(RUSTDOC)}(\S+?)(?=[)\s])", path.read_text()):
            page = doc / url.split("#", 1)[0].lstrip("/")
            if not page.exists():
                fail(f"{rel} links to {url}, which rustdoc did not build.")


def main() -> int:
    changed = False
    changed |= write("docs/reference/cli.md", cli_page())
    changed |= write("docs/reference/http.md", http_page())
    changed |= inject("docs/config.md", "keys", config_table())
    changed |= inject("docs/config.md", "count", str(known_keys()))
    check_rustdoc_links()

    if failures:
        print(f"\n{len(failures)} reference check(s) failed:\n", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    print("reference up to date." if not changed else "reference regenerated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
