#!/usr/bin/env python3
"""Record Mira driving a real investigation, and write it out as a GIF.

    make demo                            # in another terminal, or --addr any node
    python3 scripts/tui-cast.py investigation
    python3 scripts/tui-cast.py write-up

Two casts, because the story has two halves on two surfaces. `investigation` is
`mira mira`: every log, then only the ERROR ones, then who calls whom, then the
trace under the failure. `write-up` is `POST /mcp` in a shell, where `render_rca`
refuses a citation it cannot re-prove and then writes the document.

Both are recordings, not mock-ups. Every character came out of a real Mira over
the demo generator's data, and every number in them — the query plans, the record
count beside each claim — is that run's own. The only thing invented is the dwell
between frames, because a pty capture carries no clock.

Three steps, and the middle one is the only surprising one:

1.  Drive the thing on a pty of our own, with a pause after each step so it sees
    a person rather than a paste, and keep the capture length after each one.
2.  Read the capture with fifty lines rather than a terminal emulator. What both
    casts write is unusually easy: the TUI repaints from the top-left every frame
    with no cursor addressing at all, a shell only ever appends, and between them
    the vocabulary is `ESC[H`, `ESC[K`, `ESC[J` and a dozen SGR codes.
    `assert_simple` fails the run the moment that stops being true, which is the
    moment this shortcut needs replacing with a real emulator. The two differ
    only in where the frame boundaries are: `ESC[H` for a repaint, the recorder's
    byte offsets for a transcript that scrolls.
3.  Draw the cell grid with Pillow and save the frames as one GIF. GIF stores
    each frame as the rectangle that changed, so the twenty frames of typing in
    `investigation` — one row different each — cost almost nothing.

Requires Pillow and a monospaced TTF; both are on the machine that regenerates
the assets, neither is a dependency of Mira. Nothing in CI runs this — the GIFs
are committed, and regenerated by hand when what they show changes. Look at the
result: a layout that has lost content still renders perfectly well.

ponytail: `investigation` matches its scenes on what the TUI writes in its own
footer rather than on frame numbers, so a reworded keymap fails loudly here
instead of quietly picking the wrong screen. If the footers change, fix SCENES.
"""

from __future__ import annotations

import argparse
import fcntl
import json
import os
import pathlib
import pty
import re
import select
import struct
import subprocess
import sys
import tempfile
import termios
import time

from PIL import Image, ImageDraw, ImageFont

# --- the recording ---------------------------------------------------------

COLS = 112
# Rows are per-cast: the TUI is a full-screen application and wants a screen,
# while the write-up cast is a transcript that only ever has a dozen lines live
# at once — given 24 it plays out in a window two thirds empty.
ROWS, SHELL_ROWS = 24, 18

# One investigation — the same one docs/demo.md walks through in prose: every
# log, then only the ERROR ones, then who calls whom, then the trace under the
# failure. Each entry is (keys, seconds to wait after them); the waits are what
# make the pty deliver one keystroke per redraw instead of one burst.
KEYS: list[tuple[str, float]] = (
    [("", 1.5)]
    + [(c, 0.10) for c in "/severity_text=ERROR"]
    + [("\r", 1.6), ("m", 1.6), ("q", 0.8), ("t", 2.0), ("q", 0.6), ("q", 0.6)]
)

# The scenes, in the order they play, and how long each is held in milliseconds.
# "typing" expands to one scene per keystroke.
SCENES: list[tuple[str, int]] = [
    ("the unfiltered log list", 1800),
    ("typing", 90),
    ("the ERROR rows", 2800),
    ("the service map", 2800),
    ("the trace waterfall", 4200),
]

ROOT = pathlib.Path(__file__).resolve().parent.parent
BIN = ROOT / "target" / "release" / "mira"


def record(argv: list[str], script, env=None, cwd=None, rows: int = ROWS) -> tuple[bytes, list[int]]:
    """Run `argv` on a pty of our own, type `script` at it, return all it wrote.

    `script` is a list of (keys, seconds to wait after them). The waits are what
    make the pty deliver one keystroke per redraw instead of one burst. The
    second return is the length of the capture after each step, which is the
    only way a scrolling transcript can be cut back into frames — a repainting
    TUI has `ESC[H` to cut on and a shell session has nothing.

    A pty rather than `script(1)`: it takes the window size from the terminal it
    inherits, and there is no terminal here — stdin is the keystroke feeder and
    stdout is a file — so it silently records 80x24 and every capture comes out
    truncated at the right edge. Opening the pty directly is the only way to
    state the size, and it puts the keystroke timing in this process rather than
    in a shell full of `sleep`.
    """
    master, slave = pty.openpty()
    fcntl.ioctl(slave, termios.TIOCSWINSZ, struct.pack("HHHH", rows, COLS, 0, 0))

    def own_the_tty() -> None:  # the child's controlling terminal, so raw mode takes
        os.setsid()
        fcntl.ioctl(0, termios.TIOCSCTTY, 0)

    child = subprocess.Popen(
        argv, stdin=slave, stdout=slave, stderr=subprocess.STDOUT,
        preexec_fn=own_the_tty, close_fds=True, env=env, cwd=cwd,
    )
    os.close(slave)
    out, marks = bytearray(), []

    def drain(seconds: float) -> None:
        end = time.monotonic() + seconds
        while (left := end - time.monotonic()) > 0:
            if not select.select([master], [], [], left)[0]:
                return
            try:
                chunk = os.read(master, 1 << 16)
            except OSError:
                return
            if not chunk:
                return
            out.extend(chunk)

    try:
        for keys, pause in script:
            if keys:
                os.write(master, keys.encode())
            drain(pause)
            marks.append(len(out))
    finally:
        drain(0.5)
        os.close(master)
        if child.poll() is None:
            child.kill()
        child.wait()
    return bytes(out), marks


# --- the parser ------------------------------------------------------------

CSI = re.compile(r"\x1b\[([0-9;?]*)([A-Za-z])")

# The TUI's entire vocabulary. Anything outside it means the reader below has
# stopped being a safe substitute for a terminal emulator.
KNOWN_CSI = {("", "H"), ("", "K"), ("", "J"), ("2", "J"), ("?25", "l"),
             ("?25", "h"), ("?1049", "h"), ("?1049", "l")}
# 36/37/39/90 arrive from `jq`, which colours its output because the other end
# of the pty is a real tty — so the JSON in the write-up cast is syntax-coloured
# by jq itself rather than by anything here. 39 is "back to the default
# foreground", which is not the same as 0 and must not reset bold with it.
KNOWN_SGR = {"0", "1", "2", "7", "31", "32", "33", "34", "35", "36", "37", "39", "90"}

# A cell's style: (colour key, bold, dim, reverse). None is "the default fg".
DEFAULT = (None, False, False, False)


def assert_simple(text: str) -> None:
    for params, final in CSI.findall(text):
        if final == "m":
            unknown = set(params.split(";")) - KNOWN_SGR - {""}
            if unknown:
                sys.exit(f"tui-cast: unhandled SGR {sorted(unknown)}; add it to SGR_FG.")
        elif (params, final) not in KNOWN_CSI:
            sys.exit(
                f"tui-cast: the TUI now emits ESC[{params}{final}, which this reader "
                "cannot place. It assumes a full repaint from home with no cursor "
                "addressing, and that assumption is gone."
            )


def sgr(style, params: str):
    colour, bold, dim, rev = style
    for p in (params or "0").split(";"):
        p = p or "0"
        if p == "0":
            colour, bold, dim, rev = DEFAULT
        elif p == "1":
            bold = True
        elif p == "2":
            dim = True
        elif p == "7":
            rev = True
        elif p == "39":
            colour = None
        else:
            colour = p
    return (colour, bold, dim, rev)


BLANK = [(" ", DEFAULT)] * COLS


def cells_of(line: str, style):
    """One line of output as (char, style) cells, plus the style it ends in."""
    cells, i = [], 0
    while i < len(line):
        m = CSI.match(line, i)
        if m:
            if m.group(2) == "m":
                style = sgr(style, m.group(1))
            i = m.end()
            continue
        if line[i] not in "\r\n":
            cells.append((line[i], style))
        i += 1
    return cells, style


def frames(capture: bytes) -> list[list[list[tuple[str, tuple]]]]:
    """Split the capture into frames, each a ROWS x COLS grid of (char, style)."""
    text = capture.decode("utf-8", "replace")
    assert_simple(text)
    out = []
    for chunk in text.split("\x1b[H")[1:]:
        grid = []
        for line in chunk.split("\r\n"):
            cells, _ = cells_of(line, DEFAULT)
            grid.append((cells + BLANK)[:COLS])
        out.append((grid + [BLANK] * ROWS)[:ROWS])
    return out


def text_of(grid, r: int) -> str:
    return "".join(c for c, _ in grid[r]).rstrip()


def pick(all_frames) -> list[tuple[list, int]]:
    """Turn SCENES into (grid, hold-ms), matched on what the TUI says it is."""
    def footer(f):  # the keymap line: the last row with anything on it
        return next((text_of(f, r) for r in range(ROWS - 1, -1, -1) if text_of(f, r)), "")

    def mid_flight(f):  # a frame still showing the last screen's numbers
        rows = [text_of(f, r) for r in range(ROWS) if text_of(f, r)]
        return len(rows) < 2 or rows[-2].lstrip().startswith(("running", "loading"))

    settled = [f for f in all_frames if not mid_flight(f)]
    editing = [f for f in settled if text_of(f, 1).startswith(" filter> ")]
    resting = [f for f in settled if not text_of(f, 1).startswith(" filter> ")]
    body = lambda f: "\n".join(text_of(f, r) for r in range(ROWS))

    def one(name, test, pool):
        hits = [f for f in pool if test(f)]
        if not hits:
            sys.exit(f"tui-cast: no captured frame is {name}. The keymap or the footers moved.")
        # The first settled match, not the last: the screen comes back more than
        # once (backing out of the trace redraws the log list), and only the
        # first arrival still carries its own query's numbers in the footer.
        return hits[0]

    picked = []
    for name, hold in SCENES:
        if name == "typing":
            seen = set()
            for f in editing:
                if (key := text_of(f, 1)) not in seen:
                    seen.add(key)
                    picked.append((f, hold))
        elif name == "the unfiltered log list":
            picked.append((one(name, lambda f: "(none)" in text_of(f, 1), resting), hold))
        elif name == "the ERROR rows":
            picked.append((one(name, lambda f: "ERROR" in text_of(f, 2)
                               and "t trace" in footer(f), resting), hold))
        elif name == "the service map":
            picked.append((one(name, lambda f: "filter on this service" in footer(f), resting), hold))
        elif name == "the trace waterfall":
            picked.append((one(name, lambda f: "span" in footer(f) and "trace " in body(f),
                               resting), hold))
        else:
            sys.exit(f"tui-cast: SCENES names {name!r} and pick() does not know it.")
    return picked


# --- the write-up cast -----------------------------------------------------
#
# The other half of the story: an agent has finished investigating, and wants to
# publish. `render_rca` re-runs every citation before it writes a word, so the
# interesting frame is the one where it refuses.
#
# A shell session rather than the TUI, because `render_rca` has no pane — it is
# an MCP tool, and `POST /mcp` is the surface. Recorded the same way for the same
# reason: what a reader needs to believe is that the record counts beside the
# claims came out of the store, and only a recording carries that.

# The agent's findings, as they would arrive over MCP. Written to a scratch
# directory rather than committed: it is the *input* to the thing being shown,
# and a fixture on disk is one more file that can disagree with the recording.
# One citation is deliberately wrong — `CardExpired` for `CardDeclined` — which
# is the whole point of the cast, and the session corrects it in the open.
FINDINGS = {
    "jsonrpc": "2.0", "id": 1, "method": "tools/call",
    "params": {"name": "render_rca", "arguments": {
        "title": "Checkout 503s: a card decline mapped onto a retryable status",
        "from": "-45m",
        "summary": "Every checkout 503 in the window traces to one authorize call in "
                   "payments that declines the card and returns 503. Both retry layers "
                   "replay a call that can never succeed.",
        "impact": ["530 of 10,320 checkout spans failed over 45 minutes.",
                   "No data was lost; every decline was a real decline."],
        "timeline": [
            {"at": "-42m", "what": "first CardDeclined exception on payments authorize"},
            {"at": "-40m", "what": "shop-error-rate goes pending at 5.4%"},
            {"at": "-38m", "what": "card-declines fires at 30 over a threshold of 20"}],
        "root_cause": "payments returns 503 for payments.CardDeclined. A decline is a "
                      "business outcome, not a server fault, and 503 propagates unchanged "
                      "to the frontend, so both retry layers replay it.",
        "evidence": [
            {"claim": "every failing authorize carries the same exception type",
             "query": {"signal": "traces",
                       "where": [{"attr": "exception.type", "eq": "payments.CardExpired"}]}},
            {"claim": "payments logged errors throughout the window",
             "query": {"signal": "logs",
                       "where": [{"attr": "service.name", "eq": "payments"},
                                 {"field": "severity_number", "gte": 17}]}},
            {"claim": "a failing checkout, end to end",
             "trace_id": "0000000000000efb5555555555555bae"}],
        "ruled_out": ["inventory, on the same call path: 3,440 spans, zero errors"],
        "remediation": ["Return 402 for CardDeclined in payments' error mapping."],
        "verification": ["No 503 on POST /authorize for one hour after the deploy."],
        "prevention": {"name": "card-declines", "over": "5m", "when": "count > 20",
                       "severity": "warning",
                       "query": {"signal": "traces",
                                 "where": [{"attr": "exception.type",
                                            "eq": "payments.CardDeclined"}]}},
        "emit": True}},
}

# (command, seconds to wait for its output, milliseconds to hold the frame it
# leaves). A step that holds 0 leaves no frame — the two function definitions
# and the `sed` are setup a reader reads in place, not beats to pause on.
#
# Every line is under 112 columns on purpose: a wrapped command is a command a
# reader has to reassemble. `rca` and `q` exist so the four calls after them are
# short enough to read, and are defined in the open rather than hidden in a
# fixture, because the URL they post to is half of what is being shown.
def shell_steps(addr: str) -> list[tuple[str, float, int]]:
    return [
        # Nothing, first: the shell has not printed its prompt yet when the
        # recorder starts writing, and without this the tty echoes the first
        # command above the prompt that is supposed to introduce it.
        ("", 0.8, 0),
        ("# an agent has finished investigating. three claims it wants to publish:", 0.4, 0),
        ("jq -r '.params.arguments.evidence[].claim' findings.json", 1.0, 2200),
        ("", 0.3, 0),
        ("# render_rca re-runs every one of them before it writes a word.", 0.4, 0),
        (f"rca() {{ curl -s {addr}/mcp -d @\"$1\" | jq -r '.result.content[0].text'; }}", 0.5, 0),
        ("rca findings.json", 2.0, 4800),
        ("", 0.3, 0),
        ("sed s/CardExpired/CardDeclined/ findings.json > fixed.json   # the agent corrects it",
         0.6, 0),
        # No hold of its own: the line count is worth seeing, but it is still on
        # screen in the next frame and a whole beat for `59 write-up.md` is a
        # beat the reader spends not reading the evidence.
        ("rca fixed.json > write-up.md; wc -l write-up.md", 2.5, 0),
        ("grep -A4 '## Evidence' write-up.md", 1.2, 5400),
        ("", 0.3, 0),
        ("# `emit: true` stored the write-up itself. there is no incident store:", 0.4, 0),
        (f"q() {{ curl -s {addr}/api/v1/query -d \"$1\" | jq -c .stats; }}", 0.5, 0),
        ("""q '{"signal":"logs","where":[{"field":"event_name","eq":"rca"}],"limit":1}'""",
         1.5, 5000),
    ]


def record_shell(addr: str, tmp: pathlib.Path) -> tuple[bytes, list[int], list[int]]:
    """Drive a real `sh` through the session above, in a scratch directory."""
    (tmp / "findings.json").write_text(json.dumps(FINDINGS, indent=1))
    steps = shell_steps(addr)
    # A prompt of our own, in the brand colour, and nothing else: the recording
    # must not carry whoever's dotfiles are on the machine that made it. SGR 35
    # is magenta, which the TUI never emits and SGR_FG maps to rust — the same
    # licence the rest of that table takes, where "31 is red" and which red is
    # the terminal's business.
    env = {"PS1": "\x1b[35m$\x1b[0m ", "PS2": "> ", "TERM": "dumb", "HOME": str(tmp),
           "PATH": os.environ.get("PATH", "/usr/bin:/bin"), "LANG": "en_US.UTF-8"}
    capture, marks = record(
        ["/bin/sh"], [(cmd + "\r" if cmd else "", wait) for cmd, wait, _ in steps],
        env=env, cwd=tmp, rows=SHELL_ROWS,
    )
    return capture, marks, [hold for _, _, hold in steps]


def scrollback(capture: bytes, marks: list[int], holds: list[int], rows: int):
    """Cut a scrolling transcript into frames: the last ROWS lines at each mark.

    A shell does not repaint, so there is no `ESC[H` to split on — the frame at
    step n is everything written up to `marks[n]`, wrapped at the window width
    and shown from the bottom. Which is what the terminal on the other end of
    the pty was displaying at that moment, since it was doing the same sum.
    """
    text = capture.decode("utf-8", "replace").replace("\r\n", "\n").replace("\r", "")
    assert_simple(text)
    out = []
    for end, hold in zip(marks, holds):
        if not hold:
            continue
        lines, style = [], DEFAULT
        # The byte offset is into the capture; decoding a prefix of it can split
        # a multi-byte character, so cut the decoded text at the same *character*
        # count instead — `errors="replace"` keeps the two in step.
        for line in capture[:end].decode("utf-8", "replace").replace("\r\n", "\n") \
                                 .replace("\r", "").split("\n"):
            cells, style = cells_of(line, style)
            # Soft-wrap, exactly as the terminal does. A wrapped line is one the
            # reader can still read; a truncated one is a silent lie.
            for i in range(0, max(len(cells), 1), COLS):
                lines.append((cells[i:i + COLS] + BLANK)[:COLS])
        out.append(((lines[-rows:] + [BLANK] * rows)[:rows], hold))
    return out


# --- the drawing -----------------------------------------------------------

# A capture carries no colours of its own: SGR 31 is "red", and which red is the
# terminal's business. These are a choice made once — the docs site's own
# surface from stylesheets/extra.css, and GitHub-dark's ANSI over it, so a
# reader who has seen the web UI recognises the palette.
BG, FG, DIM, BRIGHT = "#0d1117", "#c9d1d9", "#6e7681", "#f0f6fc"
SGR_FG = {"31": "#ff7b72", "32": "#3fb950", "33": "#d29922", "34": "#58a6ff",
          # 35 is the shell prompt in the write-up cast and nothing else; the
          # TUI never emits it. See record_shell.
          "35": "#f74c00", "36": "#39c5cf", "37": "#b1bac4", "90": DIM}
RUST = "#f74c00"

# Menlo's advance is exactly 0.6em, so at 15px a cell is 9px wide with no
# rounding drift down a 112-column row. Change the size and check that
# `font.getlength("M")` is still an integer, or runs will walk off the grid.
FONT_SIZE = 15
CELL_W, CELL_H = 9, 20
PAD = 14
EDGE = 2  # the square two-pixel edge every panel on the docs site has
FONT_PATHS = ["/System/Library/Fonts/Menlo.ttc", "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
              "/Library/Fonts/DejaVuSansMono.ttf"]

WIDTH = PAD * 2 + COLS * CELL_W


def height_of(grid) -> int:
    return PAD * 2 + len(grid) * CELL_H


def load_font(bold: bool):
    for p in FONT_PATHS:
        if os.path.exists(p):
            # Menlo.ttc carries Regular at index 0 and Bold at 1; a plain .ttf
            # ignores the index and renders bold as regular, which is fine —
            # the TUI only ever uses bold on its own title.
            font = ImageFont.truetype(p, FONT_SIZE, index=1 if bold and p.endswith(".ttc") else 0)
            if font.getlength("M") != CELL_W:
                sys.exit(f"tui-cast: {p} advances {font.getlength('M')}px at {FONT_SIZE}px, "
                         f"not the {CELL_W}px the grid assumes.")
            return font
    sys.exit(f"tui-cast: no monospaced font found. Looked in: {', '.join(FONT_PATHS)}")


def colour_of(style) -> str:
    key, bold, dim, _ = style
    if key in SGR_FG:
        return SGR_FG[key]
    return DIM if dim else (BRIGHT if bold else FG)


def runs(cells):
    """Group a row into (column, text, style), dropping trailing blank space."""
    out, start, buf, cur = [], 0, [], None
    for i, (ch, st) in enumerate(cells):
        if st != cur:
            if buf:
                out.append((start, "".join(buf), cur))
            start, buf, cur = i, [], st
        buf.append(ch)
    if buf:
        out.append((start, "".join(buf), cur))
    return [(c, t, s) for c, t, s in out if t.strip() or s[3]]


def render(grid, fonts) -> Image.Image:
    h = height_of(grid)
    im = Image.new("RGB", (WIDTH, h), BG)
    d = ImageDraw.Draw(im)
    d.rectangle([0, 0, WIDTH - 1, h - 1], outline=RUST, width=EDGE)
    for r, cells in enumerate(grid):
        y = PAD + r * CELL_H
        for col, text, style in runs(cells):
            x = PAD + col * CELL_W
            fill = colour_of(style)
            if style[3]:  # reverse video: the run's colour becomes its background
                d.rectangle([x, y, x + len(text) * CELL_W - 1, y + CELL_H - 1], fill=fill)
                fill = BG
            if text.strip():
                d.text((x, y + 2), text, font=fonts[style[1]], fill=fill)
    return im


def to_gif(scenes, out: pathlib.Path) -> None:
    fonts = {False: load_font(False), True: load_font(True)}
    images = [render(grid, fonts) for grid, _ in scenes]
    # One palette for the whole animation, taken from the frames stacked into a
    # single image: quantising each frame on its own gives each a different
    # palette, which defeats GIF's own frame-to-frame delta and triples the file.
    # No dithering — dither noise on a flat terminal background is pure entropy.
    h = images[0].height
    stack = Image.new("RGB", (WIDTH, h * len(images)))
    for i, im in enumerate(images):
        stack.paste(im, (0, i * h))
    palette = stack.convert("P", palette=Image.Palette.ADAPTIVE, colors=64)
    quantised = [im.quantize(palette=palette, dither=Image.Dither.NONE) for im in images]
    quantised[0].save(
        out, save_all=True, append_images=quantised[1:], loop=0,
        duration=[hold for _, hold in scenes], disposal=1, optimize=True,
    )


CASTS = {"investigation": "the terminal UI, from every log to the trace under the failure",
         "write-up": "render_rca refusing a citation it cannot re-prove, then writing"}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("cast", nargs="?", default="investigation", choices=sorted(CASTS),
                    help="; ".join(f"{k}: {v}" for k, v in CASTS.items()))
    ap.add_argument("--addr", default="localhost:4318", help="a node to read; `make demo` starts one")
    ap.add_argument("--raw", type=pathlib.Path,
                    help="replay a capture instead of recording (investigation only)")
    ap.add_argument("--keep-raw", type=pathlib.Path, help="write the pty capture here too")
    ap.add_argument("--out", type=pathlib.Path, help="default: docs/assets/tui/<cast>.gif")
    args = ap.parse_args()
    out = args.out or ROOT / f"docs/assets/tui/{args.cast}.gif"

    if args.cast == "write-up":
        if args.raw:
            # The frames are cut on byte offsets the recorder returns, and a raw
            # file does not carry them. Replay is an investigation-only luxury.
            sys.exit("tui-cast: --raw cannot replay the write-up cast; it needs the marks.")
        with tempfile.TemporaryDirectory(prefix="tui-cast-") as tmp:
            capture, marks, holds = record_shell(args.addr, pathlib.Path(tmp))
        scenes = scrollback(capture, marks, holds, SHELL_ROWS)
    else:
        if args.raw:
            capture = args.raw.read_bytes()
        elif not BIN.exists():
            sys.exit(f"tui-cast: {BIN} is not built. `make build` first.")
        else:
            capture, _ = record([str(BIN), "mira", "--addr", args.addr], KEYS)
        scenes = pick(frames(capture))
    if args.keep_raw:
        args.keep_raw.write_bytes(capture)

    out.parent.mkdir(parents=True, exist_ok=True)
    to_gif(scenes, out)
    print(f"{out}  {len(scenes)} frames  "
          f"{WIDTH}x{height_of(scenes[0][0])}  {os.path.getsize(out) / 1024:.0f} KiB")


if __name__ == "__main__":
    main()
